login/urls.py
from django.urls import path
from .views import Auth
urlpatterns = [
    path('', Auth.as_view(), name='Auth'),
    ]

persona/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('question', include('question.urls')),
    path('User', include('signup.urls')),
    path('Auth', include('login.urls')),
]

question/urls.py
from django.urls import path
from .views import question
urlpatterns = [
    path('', question.as_view(), name='question'),
    ]

signup/urls.py
from django.urls import path
from .views import User
from login.views import Auth
urlpatterns = [
    path('', User.as_view(), name='User'),
    path('Auth', Auth.as_view(), name='Auth'),

    ]

login/models.py
from django.db import models

# Create your models here.

question/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms

class AuthForm(forms.Form):
    emailA = forms.CharField(label='Your Email Auth')
    passwordA = forms.CharField(label='Password Auth')

question/forms.py
from django import forms

class QuestionForm(forms.Form):
    name = forms.CharField(label='Your name')
    gender = forms.ChoiceField(
        choices=[('male', 'Male'), ('female', 'Female')],
        label='Your gender'
    )
    radio = forms.ChoiceField(
        choices=[
            ('question1', 'Are you angry in the case you lose the credit card?'),
            ('question2', 'Do you like your parents?'),
            ('question3', 'Do you like banana?')
        ],
        label='Judgement',
        widget=forms.RadioSelect
    )

signup/forms.py
from django import forms

class UserForm(forms.Form):
    name = forms.CharField(label='Your name')
    email = forms.CharField(label='Your Email')
    password = forms.CharField(label='Password')

login/views.py
from django.shortcuts import render,redirect
from django.views import View
from .forms import AuthForm
from supabase import create_client
from django.contrib.auth import authenticate, login

url = "https://your url.supabase.co"
key = "your KEY"

supabase = create_client(url, key)

class Auth(View):
    def get(self, request):
        form = AuthForm()
        return render(request, 'login/login.html', {'form': form})

    def post(self, request):
        form = AuthForm(request.POST)
        if form.is_valid():
            email = request.POST.get('email')
            raw_password = request.POST.get('password')
            user = authenticate(request, emailA=email, passwordA=raw_password)
            if user:
                login(request, user)
            return redirect('question')
        return render(request, 'login/login.html', {'form': form})    

question/views.py
from django.shortcuts import render
from django.views import View
from .forms import QuestionForm
from supabase import create_client
import os
url = "https://your url.supabase.co"
key = "your KEY"
supabase = create_client(url, key)

class question(View):
    def get(self, request):
        form = QuestionForm()
        return render(request, 'question/question.html', {'form': form})

    def post(self, request):
        form = QuestionForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            gender = form.cleaned_data['gender']
            selected_radio = form.cleaned_data['radio']

            all_options = ['question1', 'question2', 'question3']

            radio_status = {q: q == selected_radio for q in all_options}
            data = {
                "name": name,
                "gender": gender,
                "question1": radio_status['question1'],
                "question2": radio_status['question2'],
                "question3": radio_status['question3']
            }
            supabase.table("users").insert(data).execute()
        return render(request, 'question/question.html', {'form': form})

signup/views.py
from django.shortcuts import render
from django.views import View
from .forms import UserForm
from supabase import create_client
import bcrypt

url = "https://your url.supabase.co"
key = "your KEY"
supabase = create_client(url, key)

class User(View):
    def get(self, request):
        form = UserForm()
        return render(request, 'signup/index.html', {'form': form})

    def post(self, request):
        form = UserForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            hashed_pw = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()

            data = {
                "name": name,
                "email": email,
                "password": hashed_pw,
            }
            supabase.table("auth").insert(data).execute()
        return render(request, 'signup/index.html', {'form': form})    

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Log in</title>
</head>
<body>
    <h2>Log in</h2>
    {% if form.errors %}
        <p style="color:red;">email or password is false</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <label for="id_username">email:</label>
        {{ form.emailA }}
        <label for="id_password">password:</label>
        {{ form.passwordA }}
        <button type="submit">LOGIN</button>
    </form>
</body>
</html>

question/templates/question/question.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Question</title>
        {% load static %}
<link rel="stylesheet" href="{% static 'question/style.css' %}">
    </head>
    <body>
        <h2>Your gender and name</h2>
        {% if form.errors %}
        <p style="color:blue;">not correct</p>
        {% endif %}
    <form method="post">
        {% csrf_token %}
        <label for="id_gender">Your gender is:</label>
        {{ form.gender }}
        <label for="id_username">Your name is:</label>
        {{ form.name }}
        <p>Select you are YES on the next radio buttons</p>
        {{ form.radio }}
        <button type="submit">Submit</button>
    </form>
    </body>
</html>

signup/templates/signup/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Sign up</title>
</head>
<body>
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        <h2>name is :</h2>
        {{ form.name }}
        <h2>email is :</h2>
        {{ form.email }}
        <h2>password is :</h2>
        {{ form.password }}
        <button type="submit">submit</button>
    </form>
    <p><a href="{% url 'Auth' %}">Log in</a></p>
</body>
</html>